apiVersion: v1
kind: pod
metadta:
  name: souvik-pod
  namespace: souvik-ns
  lables:
    app: nginx
spec:
  containers:
    - name: souvik-container
      image: nginx:1.25
      ports:
        - containerPorts: 80