apiVersion: v1
kind: service
metadta:
  name: souvik-service-nodeport
  namespace: souvik-ns
spec:
  selector:
  matchLables:
    app: Demo
  port:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodeport: 30080
  type: NodePort
