apiVersion: v1
kind: service
metadta:
  name: souvik-service-loadbalancer
  namespace: souvik-ns
spec:
  selector:
  matchLables:
    app: Demo
  port:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
